-- MySQL Script generated by MySQL Workbench
-- Mon Jul 13 12:07:04 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mom&pop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mom&pop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mom&pop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mom&pop` ;

-- -----------------------------------------------------
-- Table `mom&pop`.`shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`shops` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `shop_type` VARCHAR(255) NOT NULL,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `allowed_radius` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`categories` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `categories_shop_id_slug_unique` (`shop_id` ASC, `slug` ASC) VISIBLE,
  CONSTRAINT `categories_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mom&pop`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`units` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `conversion_rate` DECIMAL(10,3) NOT NULL,
  `type` VARCHAR(255) NOT NULL DEFAULT 'unit',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`products` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `category_id` CHAR(36) NULL DEFAULT NULL,
  `unit_id` CHAR(36) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `cost_price` DECIMAL(10,2) NOT NULL,
  `selling_price` DECIMAL(10,2) NOT NULL,
  `is_perishable` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `products_shop_id_name_unique` (`shop_id` ASC, `name` ASC) VISIBLE,
  INDEX `products_category_id_foreign` (`category_id` ASC) VISIBLE,
  INDEX `products_unit_id_foreign` (`unit_id` ASC) VISIBLE,
  CONSTRAINT `products_category_id_foreign`
    FOREIGN KEY (`category_id`)
    REFERENCES `mom&pop`.`categories` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `products_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mom&pop`.`shops` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `products_unit_id_foreign`
    FOREIGN KEY (`unit_id`)
    REFERENCES `mom&pop`.`units` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`bottles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`bottles` (
  `id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `is_weighable` TINYINT(1) NOT NULL DEFAULT '1',
  `capacity_ml` INT NOT NULL,
  `tare_weight_g` INT NOT NULL,
  `gross_weight_g` INT NOT NULL,
  `bottle_selling_price` DECIMAL(10,2) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `bottles_product_id_unique` (`product_id` ASC) VISIBLE,
  CONSTRAINT `bottles_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `mom&pop`.`products` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`cache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`cache` (
  `key` VARCHAR(255) NOT NULL,
  `value` MEDIUMTEXT NOT NULL,
  `expiration` BIGINT NOT NULL,
  PRIMARY KEY (`key`),
  INDEX `cache_expiration_index` (`expiration` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`cache_locks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`cache_locks` (
  `key` VARCHAR(255) NOT NULL,
  `owner` VARCHAR(255) NOT NULL,
  `expiration` BIGINT NOT NULL,
  PRIMARY KEY (`key`),
  INDEX `cache_locks_expiration_index` (`expiration` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`expenses` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `type` ENUM('fixed', 'salary', 'variable') NOT NULL,
  `notes` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `expenses_shop_id_type_index` (`shop_id` ASC, `type` ASC) VISIBLE,
  CONSTRAINT `expenses_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mom&pop`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`failed_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`job_batches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`job_batches` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `total_jobs` INT NOT NULL,
  `pending_jobs` INT NOT NULL,
  `failed_jobs` INT NOT NULL,
  `failed_job_ids` LONGTEXT NOT NULL,
  `options` MEDIUMTEXT NULL DEFAULT NULL,
  `cancelled_at` INT NULL DEFAULT NULL,
  `created_at` INT NOT NULL,
  `finished_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `queue` VARCHAR(255) NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `attempts` TINYINT UNSIGNED NOT NULL,
  `reserved_at` INT UNSIGNED NULL DEFAULT NULL,
  `available_at` INT UNSIGNED NOT NULL,
  `created_at` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `jobs_queue_index` (`queue` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`migrations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`order_items` (
  `id` CHAR(36) NOT NULL,
  `orderable_type` VARCHAR(255) NOT NULL,
  `orderable_id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `metadata` VARCHAR(255) NOT NULL,
  `quantity` DECIMAL(10,3) NOT NULL,
  `unit_price` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_items_orderable_type_orderable_id_index` (`orderable_type` ASC, `orderable_id` ASC) VISIBLE,
  INDEX `order_items_product_id_foreign` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_items_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `mom&pop`.`products` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`users` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `role` VARCHAR(255) NOT NULL DEFAULT 'cashier',
  `pin` VARCHAR(255) NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE,
  INDEX `users_shop_id_foreign` (`shop_id` ASC) VISIBLE,
  CONSTRAINT `users_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mom&pop`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`shifts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`shifts` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `opened_at` TIMESTAMP NOT NULL,
  `closed_at` TIMESTAMP NULL DEFAULT NULL,
  `blind_cash_reported` DECIMAL(10,2) NULL DEFAULT NULL,
  `blind_ecocash_reported` DECIMAL(10,2) NULL DEFAULT NULL,
  `blind_swipe_reported` DECIMAL(10,2) NULL DEFAULT NULL,
  `blind_onemoney_reported` DECIMAL(10,2) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `shifts_shop_id_foreign` (`shop_id` ASC) VISIBLE,
  INDEX `shifts_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `shifts_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mom&pop`.`shops` (`id`),
  CONSTRAINT `shifts_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `mom&pop`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`orders` (
  `id` CHAR(36) NOT NULL,
  `shift_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `payment_method` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `orders_shift_id_foreign` (`shift_id` ASC) VISIBLE,
  INDEX `orders_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `orders_shift_id_foreign`
    FOREIGN KEY (`shift_id`)
    REFERENCES `mom&pop`.`shifts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `orders_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `mom&pop`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`password_reset_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`password_reset_tokens` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`personal_access_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`personal_access_tokens` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` VARCHAR(255) NOT NULL,
  `tokenable_id` BIGINT UNSIGNED NOT NULL,
  `name` TEXT NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `abilities` TEXT NULL DEFAULT NULL,
  `last_used_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `personal_access_tokens_token_unique` (`token` ASC) VISIBLE,
  INDEX `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type` ASC, `tokenable_id` ASC) VISIBLE,
  INDEX `personal_access_tokens_expires_at_index` (`expires_at` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`sessions` (
  `id` VARCHAR(255) NOT NULL,
  `user_id` CHAR(36) NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` TEXT NULL DEFAULT NULL,
  `payload` LONGTEXT NOT NULL,
  `last_activity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sessions_user_id_index` (`user_id` ASC) VISIBLE,
  INDEX `sessions_last_activity_index` (`last_activity` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`shop_owners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`shop_owners` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `shop_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `shop_owners_shop_id_user_id_unique` (`shop_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `shop_owners_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `shop_owners_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mom&pop`.`shops` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `shop_owners_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `mom&pop`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`shot_sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`shot_sizes` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `size_ml` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `shot_sizes_shop_id_unique` (`shop_id` ASC) VISIBLE,
  CONSTRAINT `shot_sizes_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mom&pop`.`shops` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`stock_variances`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`stock_variances` (
  `id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `variance` DECIMAL(10,3) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `stock_variances_product_id_created_at_index` (`product_id` ASC, `created_at` ASC) VISIBLE,
  CONSTRAINT `stock_variances_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `mom&pop`.`products` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`stocks` (
  `id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `quantity_on_hand` DECIMAL(10,3) NOT NULL DEFAULT '0.000',
  `count` DECIMAL(10,3) NOT NULL DEFAULT '0.000',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `stocks_product_id_foreign` (`product_id` ASC) VISIBLE,
  CONSTRAINT `stocks_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `mom&pop`.`products` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`tables` (
  `id` CHAR(36) NOT NULL,
  `shift_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `total_amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `payment_method` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'open',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `tables_shift_id_foreign` (`shift_id` ASC) VISIBLE,
  INDEX `tables_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `tables_shift_id_foreign`
    FOREIGN KEY (`shift_id`)
    REFERENCES `mom&pop`.`shifts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `tables_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `mom&pop`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mom&pop`.`waste_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mom&pop`.`waste_logs` (
  `id` CHAR(36) NOT NULL,
  `shop_id` CHAR(36) NOT NULL,
  `product_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `quantity` DECIMAL(10,3) NOT NULL,
  `reason` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `waste_logs_shop_id_foreign` (`shop_id` ASC) VISIBLE,
  INDEX `waste_logs_product_id_foreign` (`product_id` ASC) VISIBLE,
  INDEX `waste_logs_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `waste_logs_product_id_foreign`
    FOREIGN KEY (`product_id`)
    REFERENCES `mom&pop`.`products` (`id`),
  CONSTRAINT `waste_logs_shop_id_foreign`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mom&pop`.`shops` (`id`),
  CONSTRAINT `waste_logs_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `mom&pop`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
